### ISSUE TITLE
ColumnToggleModal checkbox change in study fields displayed when opening assay modal

### ISSUE THREAD

**Issue by sellth** [bihealth/sodar-server#1848]
### Describe the Bug
When selecting column visibility in the samplesheets app, checkbox status is mirrored across studies/assays, but not the actual column visibility. This smells like unintentional behaviour and is probably confusing to the unsuspecting user. 

### How to Reproduce
1. In Sample Sheets, enter a "Toggle Study/Assay Column Visibility" modal.
2. Change the status of some checkboxes.
3. Enter the "Toggle Study/Assay Column Visibility" modal of a second study/assay with a similar column layout.
4. Checkbox status mirrors what was set in the previously opened modal, actual column visibility is not affected.

### Expected Behavior
Column filter checkbox status should not be shared across studies/assays.

#### Assay 1
![grafik](https://github.com/bihealth/sodar-server/assets/29800411/2965382f-8cdf-4084-98a4-86148bab172f)
#### Assay 2
![grafik](https://github.com/bihealth/sodar-server/assets/29800411/dfb488f5-f382-4682-a918-011b19d788b1)

**Comment by mikkonie** [comment]
Good catch, this needs to be fixed.

**Comment by mikkonie** [comment]
This is actually very interesting. When we hit `getColumnVisibility()` and I debug print out the value of `this.columnApi.getColumn(header.field).visible`, it is the correct value. Yet the UI still displays the wrong state. Either I've made a mistake in my event handler or the bootsrap-vue element does not refresh itself correctly? In the latter case I probably need to force refresh somehow.

**Comment by mikkonie** [comment]
Fixed. Turns out I was right and the bootstrap-vue checkboxes were not correctly refreshing.

For the field elements this was easily fixed by the usual "assign random string as `:key`" trick in Vue, but for some reason this did not work for the node group checkboxes: any attempt to alter they keys changed the `$event` value to always be `true`. I'm a bit puzzled by this. In the end I decided it was no use to fight against a 3rd party component, so instead I changed the group checkboxes into a button :)
